name: CI/CD Workflow

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
# 불필요한 build_and_deploy_job 및 close_pull_request_job 제거

# 필요 시 추가 작업을 아래에 정의할 수 있습니다.
